DROP TABLE IF EXISTS lab_records CASCADE;
CREATE TABLE lab_records (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  referral_doctor_id INT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
  lab_id INT NOT NULL REFERENCES labs(id) ON DELETE CASCADE,
  type_of_test VARCHAR(20) CHECK (type_of_test IN ('BLOOD', 'URINE', 'MAMMOGRAM', 'XRAY', 'ULTRASOUND', 'MRI'))
 );